/*
 * CustomersPane.java
 */

package videostore.gui;

import videostore.controller.CustomersUseCase;
import videostore.controller.ManagementUseCase;
import videostore.model.StoreDatabase;
import videostore.model.Customer;

/** The pane associated with the "Customers" tab on the main card of the GUI
 *
 * @author Russell C. Bjork
 * 
 * MODIFIED BY: Adam Bartholomew and Steve Smith
 */
public class CustomersPane extends javax.swing.JPanel 
{
    
    /** Creates new form CustomersPane 
     */
    CustomersPane() 
    {
        initComponents();
        customerList.setModel(StoreDatabase.getInstance().getCustomerMap().listModel());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustomerButton = new javax.swing.JButton();
        customerListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList();
        editCustomerButton = new javax.swing.JButton();
        customerReportButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        customerListLabel.setText("Customers:");

        jScrollPane1.setViewportView(customerList);

        editCustomerButton.setText("Edit");
        editCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerButtonActionPerformed(evt);
            }
        });

        customerReportButton.setText("Customer Report");
        customerReportButton.setEnabled(false);
        customerReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerReportButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 452, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(addCustomerButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(customerReportButton)))
                .add(0, 122, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(229, 229, 229)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(editCustomerButton)
                    .add(customerListLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addCustomerButton)
                    .add(editCustomerButton)
                    .add(customerReportButton))
                .add(18, 18, 18)
                .add(customerListLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /** Takes the user to a new card that handles the creation of a new customer */
    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        try {
            GUI.getInstance().gotoCard("addCustomerCard");
        }
        catch(IllegalArgumentException e) {
            GUI.getInstance().showMessage(e.getMessage());
        }
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    /** Takes the user to a new card that handles the editing of a customer */
    private void editCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerButtonActionPerformed
        if(customerList.getSelectedValue() != null)
        {
            String name = customerList.getSelectedValue().toString();
            CustomersUseCase.getInstance().startEdit(name);
            GUI.getInstance().gotoCard("editCustomerCard");
        }
        else
            GUI.getInstance().showMessage("Please select a customer from the list");

    }//GEN-LAST:event_editCustomerButtonActionPerformed

    private void customerReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerReportButtonActionPerformed
        ManagementUseCase.getInstance().startCustomerReport();
    }//GEN-LAST:event_customerReportButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(ManagementUseCase.getInstance().checkManagerActivity() == true)
            customerReportButton.setEnabled(true);
        else
            customerReportButton.setEnabled(false);
    }//GEN-LAST:event_formComponentShown
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JList customerList;
    private javax.swing.JLabel customerListLabel;
    private javax.swing.JButton customerReportButton;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
