/*
 * InventoryPane.java 
 */

package videostore.gui;

import videostore.model.StoreDatabase;
import videostore.controller.ManagementUseCase;
import videostore.model.Title;

/** The pane associated with the "Inventory" tab on the main card of the GUI
 *
 * @author Russell C. Bjork
 * 
 * MODIFIED BY: Adam Bartholomew and Steve Smith
 */
public class InventoryPane extends javax.swing.JPanel 
{
    /** Creates new form InventoryPane 
     */
    InventoryPane() 
    {
        initComponents();
        titleList.setModel(StoreDatabase.getInstance().getTitlesMap().listModel());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addCopyButton = new javax.swing.JButton();
        titleListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleList = new javax.swing.JList();
        titleReportButton = new javax.swing.JButton();
        addTitleButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        addCopyButton.setText("Add Copy");
        addCopyButton.setEnabled(false);
        addCopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCopyButtonActionPerformed(evt);
            }
        });

        titleListLabel.setText("Titles:");

        jScrollPane1.setViewportView(titleList);

        titleReportButton.setText("Title Report");
        titleReportButton.setEnabled(false);
        titleReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleReportButtonActionPerformed(evt);
            }
        });

        addTitleButton.setText("Add Title");
        addTitleButton.setEnabled(false);
        addTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTitleButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(45, 45, 45)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 452, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(addTitleButton)
                                .add(48, 48, 48)
                                .add(addCopyButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(titleReportButton))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(246, 246, 246)
                        .add(titleListLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {addCopyButton, addTitleButton, titleReportButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(addTitleButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(titleReportButton)
                            .add(addCopyButton))))
                .add(18, 18, 18)
                .add(titleListLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /** Creates a new rentable item associated with a selected title */
    private void addCopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCopyButtonActionPerformed
        if(titleList.getSelectedValue() != null)
        {
            String titleName = titleList.getSelectedValue().toString();
            String itemId = "" + (StoreDatabase.getInstance().getNextItemId());
            ManagementUseCase.getInstance().startAddRentableItem(titleName);
            GUI.getInstance().showMessage("Copy of: " + titleName + " added with ID# " + itemId);
        }
        else
            GUI.getInstance().showMessage("Please select a title from the list");
    }//GEN-LAST:event_addCopyButtonActionPerformed

    /** Creates a title report */
    private void titleReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleReportButtonActionPerformed
        ManagementUseCase.getInstance().startTitleReport();
    }//GEN-LAST:event_titleReportButtonActionPerformed

    /** Takes the GUI to the add a title card */
    private void addTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTitleButtonActionPerformed
        try {
            GUI.getInstance().gotoCard("addTitle");
        }
        catch(IllegalArgumentException e) {
            GUI.getInstance().showMessage(e.getMessage());
        }
    }//GEN-LAST:event_addTitleButtonActionPerformed

    /** Enables the buttons only when a manager is logged in */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        if(ManagementUseCase.getInstance().checkManagerActivity() == true)
        {
            addTitleButton.setEnabled(true);
            addCopyButton.setEnabled(true);
            titleReportButton.setEnabled(true);
        }
        else
        {
            addTitleButton.setEnabled(false);
            addCopyButton.setEnabled(false);
            titleReportButton.setEnabled(false);            
        }
    }//GEN-LAST:event_formComponentShown
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCopyButton;
    private javax.swing.JButton addTitleButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList titleList;
    private javax.swing.JLabel titleListLabel;
    private javax.swing.JButton titleReportButton;
    // End of variables declaration//GEN-END:variables

}
